from sqlalchemy.orm import Session
import models
import schemas
import yfinance
from tdameritrade import TDAmeritrade


def fundamentals_data(db: Session, stock_id):
    stock = db.query(models.StockFundamentals).filter(models.StockFundamentals.id == stock_id).first()
    yahoo_data = yfinance.Ticker(stock.symbol)
    td_data = TDAmeritrade().get_fundamentals(stock.symbol)

    stock.ma200 = yahoo_data.info['twoHundredDayAverage']
    stock.ma50 = yahoo_data.info['fiftyDayAverage']
    stock.ebitdaMargins = yahoo_data.info['ebitdaMargins']
    stock.profitMargins = yahoo_data.info['profitMargins']
    stock.grossMargins = yahoo_data.info['grossMargins']
    stock.operatingCashflow = yahoo_data.info['operatingCashflow']
    stock.revenueGrowth = yahoo_data.info['revenueGrowth']
    stock.operatingMargins = yahoo_data.info['operatingMargins']
    stock.ebitda = yahoo_data.info['ebitda']
    stock.targetLowPrice = yahoo_data.info['targetLowPrice']
    stock.recommendationKey = yahoo_data.info['recommendationKey']
    stock.grossProfits = yahoo_data.info['grossProfits']
    stock.freeCashflow = yahoo_data.info['freeCashflow']
    stock.targetMedianPrice = yahoo_data.info['targetMedianPrice']
    stock.earningsGrowth = yahoo_data.info['earningsGrowth']
    stock.numberOfAnalystOpinions = yahoo_data.info['numberOfAnalystOpinions']
    stock.targetMeanPrice = yahoo_data.info['targetMeanPrice']
    stock.debtToEquity = yahoo_data.info['debtToEquity']
    stock.targetHighPrice = yahoo_data.info['targetHighPrice']
    stock.totalCash = yahoo_data.info['totalCash']
    stock.totalDebt = yahoo_data.info['totalDebt']
    stock.totalRevenue = yahoo_data.info['totalRevenue']
    stock.totalCashPerShare = yahoo_data.info['totalCashPerShare']
    stock.revenuePerShare = yahoo_data.info['revenuePerShare']
    stock.bookValue = yahoo_data.info['bookValue']
    stock.sharesShort = yahoo_data.info['sharesShort']
    stock.sharesPercentSharesOut = yahoo_data.info['sharesPercentSharesOut']
    stock.heldPercentInstitutions = yahoo_data.info['heldPercentInstitutions']
    stock.heldPercentInsiders = yahoo_data.info['heldPercentInsiders']
    stock.shortRatio = yahoo_data.info['shortRatio']
    stock.sharesShortPreviousMonthDate = yahoo_data.info['sharesShortPreviousMonthDate']
    stock.floatShares = yahoo_data.info['floatShares']
    stock.price = yahoo_data.info['previousClose']
    stock.forward_pe = yahoo_data.info['forwardPE']
    stock.forward_eps = yahoo_data.info['forwardEps']
    stock.company = yahoo_data.info['longName']
    stock.high52 = td_data[stock.symbol]['fundamental']['high52']
    stock.low52 = td_data[stock.symbol]['fundamental']['low52']
    stock.dividendAmount = td_data[stock.symbol]['fundamental']['dividendAmount']
    stock.dividendYield = td_data[stock.symbol]['fundamental']['dividendYield']
    if td_data[stock.symbol]['fundamental']['dividendDate'] != ' ':
        stock.dividendDate = td_data[stock.symbol]['fundamental']['dividendDate']
    stock.peRatio = td_data[stock.symbol]['fundamental']['peRatio']
    stock.pegRatio = td_data[stock.symbol]['fundamental']['pegRatio']
    stock.pbRatio = td_data[stock.symbol]['fundamental']['pbRatio']
    stock.prRatio = td_data[stock.symbol]['fundamental']['prRatio']
    stock.pcfRatio = td_data[stock.symbol]['fundamental']['pcfRatio']
    stock.grossMarginTTM = td_data[stock.symbol]['fundamental']['grossMarginTTM']
    stock.grossMarginMRQ = td_data[stock.symbol]['fundamental']['grossMarginMRQ']
    stock.netProfitMarginTTM = td_data[stock.symbol]['fundamental']['netProfitMarginTTM']
    stock.netProfitMarginMRQ = td_data[stock.symbol]['fundamental']['netProfitMarginMRQ']
    stock.operatingMarginTTM = td_data[stock.symbol]['fundamental']['operatingMarginTTM']
    stock.operatingMarginMRQ = td_data[stock.symbol]['fundamental']['operatingMarginMRQ']
    stock.returnOnEquity = td_data[stock.symbol]['fundamental']['returnOnEquity']
    stock.returnOnAssets = td_data[stock.symbol]['fundamental']['returnOnAssets']
    stock.returnOnInvestment = td_data[stock.symbol]['fundamental']['returnOnInvestment']
    stock.quickRatio = td_data[stock.symbol]['fundamental']['quickRatio']
    stock.currentRatio = td_data[stock.symbol]['fundamental']['currentRatio']
    stock.interestCoverage = td_data[stock.symbol]['fundamental']['interestCoverage']
    stock.totalDebtToCapital = td_data[stock.symbol]['fundamental']['totalDebtToCapital']
    stock.ltDebtToEquity = td_data[stock.symbol]['fundamental']['ltDebtToEquity']
    stock.epsTTM = td_data[stock.symbol]['fundamental']['epsTTM']
    stock.epsChangePercentTTM = td_data[stock.symbol]['fundamental']['epsChangePercentTTM']
    stock.epsChangeYear = td_data[stock.symbol]['fundamental']['epsChangeYear']
    stock.epsChange = td_data[stock.symbol]['fundamental']['epsChange']
    stock.revChangeYear = td_data[stock.symbol]['fundamental']['revChangeYear']
    stock.revChangeTTM = td_data[stock.symbol]['fundamental']['revChangeTTM']
    stock.revChangeIn = td_data[stock.symbol]['fundamental']['revChangeIn']
    stock.sharesOutstanding = td_data[stock.symbol]['fundamental']['sharesOutstanding']
    stock.marketCapFloat = td_data[stock.symbol]['fundamental']['marketCapFloat']
    stock.marketCap = td_data[stock.symbol]['fundamental']['marketCap']
    stock.bookValuePerShare = td_data[stock.symbol]['fundamental']['bookValuePerShare']
    stock.shortIntToFloat = td_data[stock.symbol]['fundamental']['shortIntToFloat']
    stock.shortIntDayToCover = td_data[stock.symbol]['fundamental']['shortIntDayToCover']
    stock.divGrowthRate3Year = td_data[stock.symbol]['fundamental']['divGrowthRate3Year']
    stock.beta = td_data[stock.symbol]['fundamental']['beta']
    stock.vol1DayAvg = td_data[stock.symbol]['fundamental']['vol1DayAvg']
    stock.vol10DayAvg = td_data[stock.symbol]['fundamental']['vol10DayAvg']
    stock.vol3MonthAvg = td_data[stock.symbol]['fundamental']['vol3MonthAvg']

    db.add(stock)
    db.commit()
